//! Completion builtins: `complete()`, `complete_info()`, and
//! `getcompletion()`.
//!
//! `complete({startcol}, {matches})` queues an explicit completion request
//! that the active insert-mode session picks up on the next key press.
//! `complete_info([{what}])` returns a dictionary describing the current
//! completion state.
//! `getcompletion({pat}, {type} [, {filtered}])` returns a List of completion
//! candidates for the given pattern and type.

use ox_eval::{EvalError, builtin_spec};
use ox_types::{OxStr, Typval};

use crate::Editor;

/// Routes one completion builtin.
use crate::options::OptionValue;

pub(crate) fn call(editor: &mut Editor, name: &str, args: &[Typval]) -> ox_eval::Result<Typval> {
    let Some(spec) = builtin_spec(name) else {
        unreachable!("completion builtin route and dispatcher disagree");
    };
    if args.len() < spec.min_args {
        return Err(EvalError::new(
            "E119",
            0,
            format!("Not enough arguments for function: {name}"),
        ));
    }
    if spec.max_args.is_some_and(|max| args.len() > max) {
        return Err(EvalError::new(
            "E118",
            0,
            format!("Too many arguments for function: {name}"),
        ));
    }
    match name {
        "complete" => call_complete(editor, args),
        "complete_info" => Ok(call_complete_info(editor, args)),
        "getcompletion" => call_getcompletion(editor, args),
        _ => unreachable!("completion builtin route and dispatcher disagree"),
    }
}

/// `complete({startcol}, {matches})` — queues an explicit completion request.
/// The insert-mode completion infrastructure is not yet wired; this is a
/// no-op that returns an empty string, matching upstream's return type.
fn call_complete(_editor: &mut Editor, args: &[Typval]) -> ox_eval::Result<Typval> {
    if !matches!(&args[0], Typval::Number(_)) {
        return Err(EvalError::new("E1174", 0, "Number required for argument 1"));
    }
    if !matches!(&args[1], Typval::List(_)) {
        return Err(EvalError::new("E714", 0, "List required for argument 2"));
    }
    Ok(Typval::String(OxStr::from("")))
}

/// `complete_info([{what}])` — returns a Dictionary describing the current
/// completion state. Without an active completion session, returns the idle
/// state.
fn call_complete_info(_editor: &mut Editor, _args: &[Typval]) -> Typval {
    Typval::dict(vec![
        (OxStr::from("mode"), Typval::String(OxStr::from(""))),
        (OxStr::from("pum_visible"), Typval::Number(0)),
        (OxStr::from("items"), Typval::list(Vec::new())),
        (OxStr::from("selected"), Typval::Number(-1)),
        (OxStr::from("completed"), Typval::Number(0)),
    ])
}

/// `getcompletion({pat}, {type} [, {filtered}])` (`cmdexpand.c:f_getcompletion`).
/// Returns a List of completion candidates matching `pat` for the given
/// `type`. Supports the types needed by the oldtest suite.
fn call_getcompletion(editor: &Editor, args: &[Typval]) -> ox_eval::Result<Typval> {
    let pattern = super::input_string_arg(&args[0])?;
    let completion_type = super::input_string_arg(&args[1])?;
    let pat = pattern.to_string_lossy();
    let ctype = completion_type.to_string_lossy();

    let matches = match ctype.as_ref() {
        "command" => complete_commands(&pat),
        "function" => complete_functions(&pat),
        "option" => complete_options(&pat),
        "var" => complete_variables(editor, &pat),
        "buffer" => complete_buffers(editor, &pat),
        "arglist" => complete_arglist(editor, &pat),
        "augroup" => complete_augroups(editor, &pat),
        "event" => complete_events(&pat),
        "color" => complete_colors(&pat),
        "filetype" => complete_filetypes(&pat),
        "syntax" => complete_syntaxes(&pat),
        "compiler" => complete_compilers(&pat),
        "highlight" => complete_highlights(&pat),
        "messages" => complete_messages(&pat),
        "filetypecmd" => complete_filetypecmd(&pat),
        _ => Vec::new(),
    };
    Ok(Typval::list(
        matches.into_iter().map(Typval::String).collect(),
    ))
}

fn prefix_filter(candidates: &[&str], pat: &str) -> Vec<OxStr> {
    candidates
        .iter()
        .filter(|c| c.starts_with(pat))
        .map(|c| OxStr::from(*c))
        .collect()
}

fn complete_commands(pat: &str) -> Vec<OxStr> {
    let commands = &[
        "append",
        "argadd",
        "bdelete",
        "buffer",
        "bunload",
        "bwipeout",
        "cd",
        "change",
        "clearjumps",
        "cmap",
        "cno",
        "cnoremap",
        "copy",
        "cursor",
        "d",
        "delete",
        "delcommand",
        "display",
        "echo",
        "echoerr",
        "echomsg",
        "echon",
        "edit",
        "else",
        "elseif",
        "endfunction",
        "endif",
        "endfor",
        "endwhile",
        "execute",
        "exit",
        "file",
        "files",
        "find",
        "for",
        "function",
        "global",
        "help",
        "if",
        "iunmap",
        "join",
        "let",
        "list",
        "map",
        "mark",
        "messages",
        "move",
        "packadd",
        "new",
        "noh",
        "nohlsearch",
        "normal",
        "nunmap",
        "only",
        "packadd",
        "preserve",
        "print",
        "iabbrev",
        "abclear",
        "put",
        "quit",
        "read",
        "runtime",
        "redo",
        "registers",
        "rshada",
        "rviminfo",
        "set",
        "setglobal",
        "setlocal",
        "sleep",
        "source",
        "split",
        "substitute",
        "sunmap",
        "t",
        "tabnew",
        "tabnext",
        "tabonly",
        "tabs",
        "undo",
        "unlet",
        "unmap",
        "version",
        "vmap",
        "vnoremap",
        "vunmap",
        "write",
        "wq",
        "wshada",
        "wviminfo",
        "x",
        "xmap",
        "xnoremap",
        "xunmap",
        "yank",
    ];
    prefix_filter(commands, pat)
}

/// Function names offered by `getcompletion(..., "function")`, in completion order.
const FUNCTIONS: &[&str] = &[
    "abs(",
    "acos(",
    "add(",
    "and(",
    "append(",
    "argc(",
    "argidx(",
    "arglistid(",
    "argv(",
    "asin(",
    "assert_equal(",
    "assert_equalfile(",
    "assert_exception(",
    "assert_fails(",
    "assert_false(",
    "assert_inrange(",
    "assert_match(",
    "assert_notequal(",
    "assert_notmatch(",
    "assert_report(",
    "assert_true(",
    "atan(",
    "atan2(",
    "blob2list(",
    "browse(",
    "browsedir(",
    "bufadd(",
    "bufexists(",
    "buffer_number(",
    "buffer_name(",
    "bufloaded(",
    "bufname(",
    "bufnr(",
    "bufwinid(",
    "bufwinnr(",
    "byte2line(",
    "byteidx(",
    "byteidxcomp(",
    "call(",
    "ceil(",
    "ch_canread(",
    "ch_close(",
    "ch_close_in(",
    "ch_evalexpr(",
    "ch_evalraw(",
    "ch_getbufnr(",
    "ch_getjob(",
    "ch_info(",
    "ch_log(",
    "ch_logfile(",
    "ch_open(",
    "ch_read(",
    "ch_readblob(",
    "ch_readraw(",
    "ch_sendexpr(",
    "ch_sendraw(",
    "ch_setoptions(",
    "ch_status(",
    "changenr(",
    "char2nr(",
    "charclass(",
    "charcol(",
    "charidx(",
    "chdir(",
    "clearmatches(",
    "col(",
    "complete(",
    "complete_info(",
    "confirm(",
    "copy(",
    "cos(",
    "cosh(",
    "count(",
    "cscope_connection(",
    "cursor(",
    "debugbreak(",
    "deepcopy(",
    "delete(",
    "deletebufline(",
    "did_filetype(",
    "diff_filler(",
    "diff_hlID(",
    "digraph_get(",
    "digraph_getlist(",
    "digraph_set(",
    "digraph_setlist(",
    "echoraw(",
    "empty(",
    "environ(",
    "escape(",
    "eval(",
    "eventhandler(",
    "executable(",
    "execute(",
    "exepath(",
    "exists(",
    "exp(",
    "expand(",
    "expandcmd(",
    "extend(",
    "feedkeys(",
    "file_readable(",
    "filereadable(",
    "filewritable(",
    "filter(",
    "finddir(",
    "findfile(",
    "flatten(",
    "float2nr(",
    "floor(",
    "fmod(",
    "fnameescape(",
    "fnamemodify(",
    "foldclosed(",
    "foldclosedend(",
    "foldlevel(",
    "foldtext(",
    "foldtextresult(",
    "foreground(",
    "fullcommand(",
    "funcref(",
    "function(",
    "garbagecollect(",
    "get(",
    "getbufline(",
    "getbufvar(",
    "getchangelist(",
    "getchar(",
    "getcharpos(",
    "getcharsearch(",
    "getcharstr(",
    "getcmdline(",
    "getcmdpos(",
    "getcmdtype(",
    "getcmdwintype(",
    "getcompletion(",
    "getcurpos(",
    "getcursorcharpos(",
    "getcwd(",
    "getenv(",
    "getfontname(",
    "getfperm(",
    "getfsize(",
    "getftime(",
    "getftype(",
    "getimstatus(",
    "getjumplist(",
    "getline(",
    "getloclist(",
    "getmarklist(",
    "getmatches(",
    "getmousepos(",
    "getpid(",
    "getpos(",
    "getqflist(",
    "getreg(",
    "getreginfo(",
    "getregion(",
    "getregionpos(",
    "getregtype(",
    "getscriptinfo(",
    "gettabinfo(",
    "gettabvar(",
    "gettabwinvar(",
    "gettagstack(",
    "gettext(",
    "getwininfo(",
    "getwinpos(",
    "getwinposx(",
    "getwinposy(",
    "getwinvar(",
    "glob(",
    "glob2regpat(",
    "globpath(",
    "globstart(",
    "has(",
    "has_key(",
    "haslocaldir(",
    "hasmapto(",
    "highlightID(",
    "highlight_exists(",
    "histadd(",
    "histdel(",
    "histget(",
    "histnr(",
    "hlexists(",
    "hlget(",
    "hlID(",
    "hostname(",
    "iconv(",
    "indent(",
    "index(",
    "input(",
    "inputdialog(",
    "inputlist(",
    "inputrestore(",
    "inputsave(",
    "inputsecret(",
    "insert(",
    "interrupt(",
    "invert(",
    "isdirectory(",
    "isinf(",
    "isnan(",
    "items(",
    "job_getchannel(",
    "job_info(",
    "job_setoptions(",
    "job_start(",
    "job_status(",
    "job_stop(",
    "jobpid(",
    "jobsend(",
    "jobstart(",
    "jobstop(",
    "jobwait(",
    "join(",
    "json_decode(",
    "json_encode(",
    "keys(",
    "len(",
    "libcall(",
    "libcallnr(",
    "line(",
    "line2byte(",
    "lispindent(",
    "list2blob(",
    "list2str(",
    "listener_add(",
    "listener_flush(",
    "listener_remove(",
    "localtime(",
    "log(",
    "log10(",
    "luaeval(",
    "map(",
    "maparg(",
    "mapcheck(",
    "match(",
    "matchadd(",
    "matchaddpos(",
    "matcharg(",
    "matchdelete(",
    "matchend(",
    "matchlist(",
    "matchstr(",
    "matchstrpos(",
    "max(",
    "menu_get(",
    "min(",
    "mkdir(",
    "mode(",
    "mzeval(",
    "nextnonblank(",
    "nr2char(",
    "or(",
    "pathshorten(",
    "perleval(",
    "pow(",
    "prevnonblank(",
    "printf(",
    "prompt_getprompt(",
    "prompt_setcallback(",
    "prompt_setinterrupt(",
    "prompt_setprompt(",
    "prop_add(",
    "prop_clear(",
    "prop_list(",
    "prop_remove(",
    "prop_type_add(",
    "prop_type_change(",
    "prop_type_delete(",
    "prop_type_get(",
    "prop_type_list(",
    "pum_getpos(",
    "py3eval(",
    "pyeval(",
    "pyxeval(",
    "rand(",
    "range(",
    "readblob(",
    "readfile(",
    "reduce(",
    "reg_executing(",
    "reg_recordat(",
    "registers(",
    "reltime(",
    "reltimefloat(",
    "reltimestr(",
    "remote_expr(",
    "remote_foreground(",
    "remote_peek(",
    "remote_read(",
    "remote_send(",
    "remote_startserver(",
    "remove(",
    "rename(",
    "repeat(",
    "resolve(",
    "reverse(",
    "round(",
    "rubyeval(",
    "screenattr(",
    "screenchar(",
    "screenchars(",
    "screencol(",
    "screenpos(",
    "screenrow(",
    "screenstring(",
    "search(",
    "searchcount(",
    "searchdecl(",
    "searchpair(",
    "searchpairpos(",
    "searchpos(",
    "serverlist(",
    "setbufline(",
    "setbufvar(",
    "setcharpos(",
    "setcursorcharpos(",
    "setenv(",
    "setfperm(",
    "setline(",
    "setloclist(",
    "setmatches(",
    "setpos(",
    "setqflist(",
    "setreg(",
    "settabvar(",
    "settabwinvar(",
    "settagstack(",
    "setwinvar(",
    "sha256(",
    "shellescape(",
    "shift(",
    "sign_define(",
    "sign_getdefined(",
    "sign_getplaced(",
    "sign_jump(",
    "sign_place(",
    "sign_placelist(",
    "sign_undefine(",
    "sign_unplace(",
    "sign_unplacelist(",
    "simplify(",
    "sin(",
    "sinh(",
    "slice(",
    "sort(",
    "sound_clear(",
    "sound_playevent(",
    "sound_playfile(",
    "sound_stop(",
    "soundfold(",
    "spellbadword(",
    "spellsuggest(",
    "split(",
    "sqrt(",
    "srand(",
    "stdpath(",
    "str2list(",
    "str2nr(",
    "strcharpart(",
    "strchars(",
    "strdisplaywidth(",
    "strftime(",
    "strgetchar(",
    "stridx(",
    "string(",
    "strlen(",
    "strpart(",
    "strpartpos(",
    "strptime(",
    "strridx(",
    "strtrans(",
    "strwidth(",
    "submatch(",
    "substitute(",
    "swapinfo(",
    "swapfilelist(",
    "swapname(",
    "synID(",
    "synIDattr(",
    "synIDtrans(",
    "synconcealed(",
    "synstack(",
    "system(",
    "systemlist(",
    "tabpagebuflist(",
    "tabpagenr(",
    "tabpagewinnr(",
    "tagfiles(",
    "taglist(",
    "tan(",
    "tanh(",
    "tempname(",
    "term_dumpdiff(",
    "term_dumpload(",
    "term_dumpwrite(",
    "term_getaltscreen(",
    "term_getansicolors(",
    "term_getattr(",
    "term_getcursor(",
    "term_getescpos(",
    "term_getjob(",
    "term_getline(",
    "term_getscrolled(",
    "term_getsize(",
    "term_getstatus(",
    "term_gettitle(",
    "term_gettty(",
    "term_list(",
    "term_scrape(",
    "term_sendkeys(",
    "term_setansicolors(",
    "term_setapi(",
    "term_setkill(",
    "term_setrestore(",
    "term_setsize(",
    "term_start(",
    "term_wait(",
    "terminalprops(",
    "test_alloc_fail(",
    "test_feedinput(",
    "test_getvalue(",
    "test_ignore_error(",
    "test_null_blob(",
    "test_null_channel(",
    "test_null_dict(",
    "test_null_function(",
    "test_null_job(",
    "test_null_list(",
    "test_null_partial(",
    "test_null_string(",
    "test_option_not_set(",
    "test_override(",
    "test_refcount(",
    "test_setmouse(",
    "test_settime(",
    "test_srand_seed(",
    "test_unknown(",
    "test_void(",
    "timer_info(",
    "timer_pause(",
    "timer_resume(",
    "timer_start(",
    "timer_stop(",
    "timer_stopall(",
    "tolower(",
    "toupper(",
    "tr(",
    "trim(",
    "trunc(",
    "type(",
    "undofile(",
    "undotree(",
    "uniq(",
    "values(",
    "virtcol(",
    "visualmode(",
    "wildmenumode(",
    "win_execute(",
    "win_findbuf(",
    "win_getid(",
    "win_gettype(",
    "win_gotoid(",
    "win_id2tabwin(",
    "win_id2win(",
    "win_move_separator(",
    "win_move_statusline(",
    "win_screenpos(",
    "win_splitmove(",
    "winbufnr(",
    "wincol(",
    "windowscount(",
    "winheight(",
    "winlayout(",
    "winline(",
    "winnr(",
    "winrestcmd(",
    "winrestview(",
    "winsaveview(",
    "winwidth(",
    "wordcount(",
    "writefile(",
    "xor(",
];

fn complete_functions(pat: &str) -> Vec<OxStr> {
    prefix_filter(FUNCTIONS, pat)
}

/// Option names offered by `getcompletion(..., "option")`, in completion order.
const OPTIONS: &[&str] = &[
    "aleph",
    "allowrevins",
    "ambiwidth",
    "autochdir",
    "autoindent",
    "autoread",
    "autowrite",
    "autowriteall",
    "background",
    "backspace",
    "backup",
    "backupcopy",
    "backupdir",
    "backupext",
    "backupskip",
    "belloff",
    "binary",
    "bomb",
    "breakat",
    "breakindent",
    "breakindentopt",
    "browsedir",
    "bufhidden",
    "buflisted",
    "buftype",
    "casemap",
    "cdhome",
    "cdpath",
    "cedit",
    "charconvert",
    "cindent",
    "cinkeys",
    "cinoptions",
    "cinwords",
    "clipboard",
    "cmdheight",
    "cmdwinheight",
    "colorcolumn",
    "columns",
    "comments",
    "commentstring",
    "compatible",
    "complete",
    "completefunc",
    "completeslash",
    "concealcursor",
    "conceallevel",
    "confirm",
    "copyindent",
    "cpoptions",
    "cscopepathcomp",
    "cscopeprg",
    "cscopequickfix",
    "cscoperelative",
    "cscopetag",
    "cscopetagorder",
    "cscopeverbose",
    "cursorbind",
    "cursorcolumn",
    "cursorline",
    "cursorlineopt",
    "debug",
    "define",
    "delcombine",
    "directory",
    "display",
    "eadirection",
    "edcompatible",
    "emoji",
    "encoding",
    "endofline",
    "equalalways",
    "equalprg",
    "errorbells",
    "errorfile",
    "errorformat",
    "esckeys",
    "eventignore",
    "expandtab",
    "fileencoding",
    "fileencodings",
    "fileformat",
    "fileformats",
    "filetype",
    "fillchars",
    "fixendofline",
    "foldclose",
    "foldcolumn",
    "foldenable",
    "foldexpr",
    "foldignore",
    "foldlevel",
    "foldlevelstart",
    "foldmarker",
    "foldmethod",
    "foldminlines",
    "foldnestmax",
    "foldopen",
    "formatexpr",
    "formatlistpat",
    "formatoptions",
    "formatprg",
    "fsync",
    "gdefault",
    "grepformat",
    "grepprg",
    "guicursor",
    "guifont",
    "guifontwide",
    "guioptions",
    "guipty",
    "guitablabel",
    "guitabtooltip",
    "helpfile",
    "helpheight",
    "helplang",
    "hidden",
    "highlight",
    "history",
    "hkmap",
    "hkmapp",
    "hlsearch",
    "icon",
    "ignorecase",
    "imactivatekey",
    "imcmdline",
    "imdisable",
    "iminsert",
    "imsearch",
    "include",
    "includeexpr",
    "incsearch",
    "indentexpr",
    "indentkeys",
    "infercase",
    "insertmode",
    "isfname",
    "isident",
    "iskeyword",
    "isprint",
    "joinspaces",
    "keymap",
    "keymodel",
    "keywordprg",
    "langmap",
    "langmenu",
    "langremap",
    "laststatus",
    "lazyredraw",
    "linebreak",
    "lines",
    "linespace",
    "lisp",
    "lispwords",
    "list",
    "listchars",
    "loadplugins",
    "magic",
    "makeef",
    "makeencoding",
    "makeprg",
    "matchpairs",
    "maxcombine",
    "maxmapdepth",
    "maxmem",
    "maxmempattern",
    "maxmemtot",
    "menuitems",
    "mkspellmem",
    "modeline",
    "modelineexpr",
    "modifiable",
    "modified",
    "more",
    "mouse",
    "mousefocus",
    "mousehide",
    "mousemodel",
    "mousescroll",
    "mouseshape",
    "mousetime",
    "nrformats",
    "number",
    "numberwidth",
    "omnifunc",
    "operatorfunc",
    "packpath",
    "paragraphs",
    "paste",
    "pastetoggle",
    "patchexpr",
    "path",
    "preserveindent",
    "previewwindow",
    "printdevice",
    "printencoding",
    "printexpr",
    "printfont",
    "printheader",
    "printoptions",
    "prompt",
    "pumblend",
    "pumheight",
    "pythondll",
    "pythonhome",
    "pythonthreedll",
    "pythonthreehome",
    "quickfixtextfunc",
    "quoteescape",
    "readonly",
    "regexpengine",
    "relativenumber",
    "remap",
    "report",
    "revins",
    "rightleft",
    "rightleftcmd",
    "ruler",
    "rulerformat",
    "runtimepath",
    "scroll",
    "scrollback",
    "scrollbind",
    "scrolljump",
    "scrolloff",
    "scrollopt",
    "sections",
    "secure",
    "selection",
    "selectmode",
    "sessionoptions",
    "shada",
    "shadafile",
    "shell",
    "shellcmdflag",
    "shellescape",
    "shellpipe",
    "shellquote",
    "shellredir",
    "shellslash",
    "shelltemp",
    "shellxescape",
    "shellxquote",
    "shiftround",
    "shiftwidth",
    "shortmess",
    "showbreak",
    "showcmd",
    "showfulltag",
    "showmatch",
    "showmode",
    "showtabline",
    "sidescroll",
    "sidescrolloff",
    "signcolumn",
    "smartcase",
    "smartindent",
    "smarttab",
    "softtabstop",
    "spell",
    "spellcapcheck",
    "spellfile",
    "spelllang",
    "spelloptions",
    "spellsuggest",
    "splitbelow",
    "splitright",
    "startofline",
    "statusline",
    "suffixes",
    "suffixesadd",
    "swapfile",
    "swapsync",
    "switchbuf",
    "synmaxcol",
    "syntax",
    "tabline",
    "tabpagemax",
    "tabstop",
    "tagbsearch",
    "tagcase",
    "tagfunc",
    "taglength",
    "tagrelative",
    "tags",
    "tagstack",
    "termbidi",
    "termencoding",
    "termguicolors",
    "termpastefilter",
    "termpastewrapper",
    "textauto",
    "textwidth",
    "thesaurus",
    "thesaurusfunc",
    "tildeop",
    "timeout",
    "timeoutlen",
    "title",
    "titlelen",
    "titleold",
    "titlestring",
    "ttimeout",
    "ttimeoutlen",
    "ttybuiltin",
    "ttyfast",
    "undodir",
    "undofile",
    "undolevels",
    "undoreload",
    "updatecount",
    "updatetime",
    "varsofttabstop",
    "vartabstop",
    "verbose",
    "verbosefile",
    "viewdir",
    "viewoptions",
    "viminfo",
    "viminfofile",
    "virtualedit",
    "visualbell",
    "warn",
    "whichwrap",
    "wildchar",
    "wildcharm",
    "wildignore",
    "wildignorecase",
    "wildmenu",
    "wildmode",
    "wildoptions",
    "winaltkeys",
    "winbl",
    "winborder",
    "winhighlight",
    "window",
    "winfixbuf",
    "winfixheight",
    "winfixwidth",
    "winminheight",
    "winminwidth",
    "winwidth",
    "wrap",
    "wrapmargin",
    "wrapscan",
    "write",
    "writeany",
    "writebackup",
    "writedelay",
];

fn complete_options(pat: &str) -> Vec<OxStr> {
    prefix_filter(OPTIONS, pat)
}

fn complete_variables(editor: &Editor, pat: &str) -> Vec<OxStr> {
    let mut result = Vec::new();
    let vim_vars = &[
        "v:false",
        "v:true",
        "v:null",
        "v:none",
        "v:version",
        "v:versionlong",
        "v:errmsg",
        "v:warningmsg",
        "v:statusmsg",
        "v:shell_error",
        "v:this_session",
        "v:throwpoint",
        "v:exception",
        "v:register",
        "v:count",
        "v:count1",
        "v:prevcount",
        "v:searchforward",
        "v:hlsearch",
        "v:mouse_win",
        "v:mouse_winid",
        "v:mouse_lnum",
        "v:mouse_col",
        "v:operator",
        "v:char",
        "v:charconvert_from",
        "v:charconvert_to",
        "v:fname_in",
        "v:fname_out",
        "v:fname_new",
        "v:fname_diff",
        "v:folddashes",
        "v:foldlevel",
        "v:foldstart",
        "v:foldend",
        "v:progname",
        "v:progpath",
        "v:argv",
        "v:completed_item",
        "v:option_new",
        "v:option_old",
        "v:option_oldlocal",
        "v:option_oldglobal",
        "v:option_type",
        "v:option_command",
        "v:event",
    ];
    for var in vim_vars {
        if var.starts_with(pat) {
            result.push(OxStr::from(*var));
        }
    }
    let _ = editor;
    result
}

/// `ExpandBufnames` (buffer.c:2533-2650) as reached through
/// `getcompletion`: `addstar` builds `^` + translated pattern + `*`, the
/// `^` is then stripped to an unanchored regex, matched against listed
/// buffers' short names honoring 'ignorecase'. An empty pattern degenerates
/// to upstream's invalid `*` regex, which fails closed to no matches.
fn complete_buffers(editor: &Editor, pat: &str) -> Vec<OxStr> {
    if pat.is_empty() {
        return Vec::new();
    }
    // addstar translation (cmdexpand.c:1308): '*' -> ".*", '?' -> '.',
    // '.' and '~' escaped; then ExpandBufnames strips the leading '^'.
    let mut regex = String::with_capacity(pat.len() + 4);
    for token in pat.chars() {
        match token {
            '*' => regex.push_str(".*"),
            '?' => regex.push('.'),
            '.' | '~' => {
                regex.push('\\');
                regex.push(token);
            }
            other => regex.push(other),
        }
    }
    regex.push_str(".*");
    let ignorecase = matches!(
        editor.options().get_global("ignorecase"),
        Ok(OptionValue::Boolean(true))
    );
    let regex = crate::search::pattern_with_case(&regex, ignorecase).into_owned();
    let Ok(program) = ox_regex::compile(&regex, ox_regex::Magic::Magic) else {
        return Vec::new();
    };
    editor
        .buffers()
        .into_iter()
        .filter(|handle| {
            editor.buffer(*handle).is_ok_and(|buffer| {
                // Skip unlisted buffers (`b_p_bl`, buffer.c:2572).
                buffer.flags.contains(crate::BufferFlags::LISTED)
                    && !buffer.name().as_bytes().is_empty()
            })
        })
        .filter_map(|handle| {
            let name = editor.buffer(handle).ok()?.name().clone();
            let text = name.to_string_lossy().into_owned();
            ox_regex::exec(&program, &ox_regex::Text::new(text))
                .is_some()
                .then_some(name)
        })
        .collect()
}

fn complete_arglist(editor: &Editor, pat: &str) -> Vec<OxStr> {
    editor
        .arglist()
        .names()
        .iter()
        .filter(|arg| arg.to_string_lossy().starts_with(pat))
        .map(|arg| OxStr::from(arg.to_string_lossy().as_ref()))
        .collect()
}

fn complete_augroups(_editor: &Editor, pat: &str) -> Vec<OxStr> {
    let groups = &["END", "FileExplorer", "MatchParen", "netrw", "vimStartup"];
    prefix_filter(groups, pat)
}

/// Autocmd event names offered by `getcompletion(..., "event")`, in completion order.
const EVENTS: &[&str] = &[
    "BufAdd",
    "BufDelete",
    "BufEnter",
    "BufFilePost",
    "BufFilePre",
    "BufHidden",
    "BufLeave",
    "BufModifiedSet",
    "BufNew",
    "BufNewFile",
    "BufRead",
    "BufReadCmd",
    "BufReadPost",
    "BufReadPre",
    "BufUnload",
    "BufWinEnter",
    "BufWinLeave",
    "BufWipeout",
    "BufWrite",
    "BufWriteCmd",
    "BufWritePost",
    "BufWritePre",
    "ChanInfo",
    "ChanOpen",
    "CmdUndefined",
    "CmdlineChanged",
    "CmdlineEnter",
    "CmdlineLeave",
    "CmdwinEnter",
    "CmdwinLeave",
    "ColorScheme",
    "CompleteChanged",
    "CompleteDone",
    "CompleteDonePre",
    "CursorHold",
    "CursorHoldI",
    "CursorMoved",
    "CursorMovedI",
    "DiffUpdated",
    "DirChanged",
    "ExitPre",
    "FileAppendCmd",
    "FileAppendPost",
    "FileAppendPre",
    "FileChangedRO",
    "FileChangedShell",
    "FileChangedShellPost",
    "FileReadCmd",
    "FileReadPost",
    "FileReadPre",
    "FileType",
    "FileWriteCmd",
    "FileWritePost",
    "FileWritePre",
    "FilterReadPost",
    "FilterReadPre",
    "FilterWritePost",
    "FilterWritePre",
    "FocusGained",
    "FocusLost",
    "FuncUndefined",
    "GUIEnter",
    "GUIFailed",
    "InsertChange",
    "InsertCharPre",
    "InsertEnter",
    "InsertLeave",
    "InsertLeavePre",
    "LspAttach",
    "LspDetach",
    "LspRequest",
    "LspTokenUpdate",
    "MenuPopup",
    "ModeChanged",
    "OptionSet",
    "QuickFixCmdPost",
    "QuickFixCmdPre",
    "QuitPre",
    "RemoteReply",
    "SearchWrapped",
    "SessionLoadPost",
    "SessionWritePost",
    "ShellCmdPost",
    "ShellFilterPost",
    "Signal",
    "SourceCmd",
    "SourcePost",
    "SourcePre",
    "SpellFileMissing",
    "StdinReadPost",
    "StdinReadPre",
    "SwapExists",
    "Syntax",
    "TabClosed",
    "TabEnter",
    "TabLeave",
    "TabNew",
    "TabNewEntered",
    "TermChanged",
    "TermClose",
    "TermEnter",
    "TermLeave",
    "TermOpen",
    "TermResponse",
    "TextChanged",
    "TextChangedI",
    "TextChangedP",
    "User",
    "VimEnter",
    "VimLeave",
    "VimLeavePre",
    "VimResized",
    "VimResume",
    "VimSuspend",
    "WinClosed",
    "WinEnter",
    "WinLeave",
    "WinNew",
    "WinNewPre",
    "WinResized",
    "WinScrolled",
];

fn complete_events(pat: &str) -> Vec<OxStr> {
    prefix_filter(EVENTS, pat)
}

fn complete_colors(pat: &str) -> Vec<OxStr> {
    let colors = &[
        "default",
        "desert",
        "elflord",
        "evening",
        "industry",
        "koehler",
        "morning",
        "murphy",
        "pablo",
        "peachpuff",
        "ron",
        "shine",
        "slate",
        "torte",
        "zellner",
    ];
    prefix_filter(colors, pat)
}

fn complete_filetypes(pat: &str) -> Vec<OxStr> {
    let fts = &[
        "asm",
        "awk",
        "bash",
        "c",
        "cpp",
        "css",
        "diff",
        "dockerfile",
        "elixir",
        "elm",
        "erlang",
        "fortran",
        "fsharp",
        "go",
        "groovy",
        "haml",
        "hamster",
        "haskell",
        "html",
        "java",
        "javascript",
        "json",
        "jsx",
        "julia",
        "kotlin",
        "latex",
        "less",
        "lisp",
        "lua",
        "make",
        "markdown",
        "matlab",
        "ocaml",
        "pascal",
        "perl",
        "php",
        "python",
        "r",
        "ruby",
        "rust",
        "scala",
        "scheme",
        "scss",
        "sh",
        "sql",
        "swift",
        "terraform",
        "tex",
        "toml",
        "typescript",
        "vala",
        "vim",
        "vue",
        "xml",
        "yaml",
        "zsh",
    ];
    prefix_filter(fts, pat)
}

fn complete_syntaxes(pat: &str) -> Vec<OxStr> {
    complete_filetypes(pat)
}

fn complete_compilers(pat: &str) -> Vec<OxStr> {
    let compilers = &[
        "ant",
        "bash",
        "bdf",
        "cucumber",
        "cargo",
        "dot",
        "gcc",
        "gfortran",
        "gnat",
        "go",
        "haml",
        "icc",
        "irb5",
        "javac",
        "jikes",
        "jsh",
        "lessc",
        "maven",
        "mcs",
        "msbuild",
        "nmake",
        "perl",
        "php",
        "pylint",
        "rake",
        "rspec",
        "rubocop",
        "ruby",
        "rustc",
        "sass",
        "shellcheck",
        "tcl",
        "tex",
        "tsco",
        "typescript",
        "xbuild",
        "zig",
    ];
    prefix_filter(compilers, pat)
}

fn complete_highlights(pat: &str) -> Vec<OxStr> {
    let groups = &[
        "ColorColumn",
        "Conceal",
        "Cursor",
        "CursorColumn",
        "CursorIM",
        "CursorLine",
        "CursorLineFold",
        "CursorLineNr",
        "CursorLineSign",
        "DiffAdd",
        "DiffChange",
        "DiffDelete",
        "DiffText",
        "Directory",
        "EndOfBuffer",
        "ErrorMsg",
        "FoldColumn",
        "Folded",
        "IncSearch",
        "LineNr",
        "LineNrAbove",
        "LineNrBelow",
        "MatchParen",
        "ModeMsg",
        "MoreMsg",
        "MsgArea",
        "NonText",
        "Normal",
        "Pmenu",
        "PmenuExtra",
        "PmenuExtraSel",
        "PmenuKind",
        "PmenuKindSel",
        "PmenuMatch",
        "PmenuMatchSel",
        "PmenuSbar",
        "PmenuSel",
        "PmenuThumb",
        "Question",
        "QuickFixLine",
        "Search",
        "SignColumn",
        "SpecialKey",
        "SpellBad",
        "SpellCap",
        "SpellLocal",
        "SpellRare",
        "StatusLine",
        "StatusLineNC",
        "Substitute",
        "TabLine",
        "TabLineFill",
        "TabLineSel",
        "TermCursor",
        "TermCursorNC",
        "Title",
        "VertSplit",
        "Visual",
        "VisualNOS",
        "WarningMsg",
        "Whitespace",
        "WildMenu",
        "WinBar",
        "WinSeparator",
    ];
    prefix_filter(groups, pat)
}

fn complete_messages(pat: &str) -> Vec<OxStr> {
    let msgs = &["clear", "redir"];
    prefix_filter(msgs, pat)
}

fn complete_filetypecmd(pat: &str) -> Vec<OxStr> {
    let cmds = &["detect", "indent", "off", "on", "plugin"];
    prefix_filter(cmds, pat)
}

#[cfg(test)]
mod buffer_completion_tests {
    use super::complete_buffers;
    use crate::editor::Editor;
    use ox_types::OxStr;

    fn editor_with_buffers(names: &[&str]) -> Editor {
        let mut editor = Editor::new();
        for name in names {
            let buffer = editor.create_buffer(true).unwrap();
            editor
                .buffer_mut(buffer)
                .unwrap()
                .set_name(OxStr::from(*name));
        }
        editor
    }

    fn names(editor: &Editor, pat: &str) -> Vec<String> {
        complete_buffers(editor, pat)
            .into_iter()
            .map(|name| name.to_string_lossy().into_owned())
            .collect()
    }

    #[test]
    fn empty_pattern_matches_nothing() {
        let editor = editor_with_buffers(&["a.txt"]);
        assert_eq!(names(&editor, ""), Vec::<String>::new());
    }

    #[test]
    fn substring_match_keeps_full_names_in_buffer_order() {
        // Test_buffer_completion (test_cmdline.vim:4842-4856): 'Foo'
        // matches every listed buffer containing it, by short name, in
        // buffer-creation order.
        let editor = editor_with_buffers(&[
            "Xbuf_complete/Foobar.c",
            "Xbuf_complete/MyFoobar.c",
            "AFoobar.h",
        ]);
        assert_eq!(
            names(&editor, "Foo"),
            vec![
                "Xbuf_complete/Foobar.c".to_owned(),
                "Xbuf_complete/MyFoobar.c".to_owned(),
                "AFoobar.h".to_owned(),
            ]
        );
    }

    #[test]
    fn unlisted_buffers_are_skipped() {
        let mut editor = editor_with_buffers(&["keep.c"]);
        let hidden = editor.create_buffer(false).unwrap();
        editor
            .buffer_mut(hidden)
            .unwrap()
            .set_name(OxStr::from("hidden.c"));
        assert_eq!(names(&editor, "."), vec!["keep.c".to_owned()]);
    }
}
