[package]
name = "ox-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "server-side UI event emission, grid model, compositor."

[dependencies]
ox-editor = { path = "../ox-editor" }
ox-rpc = { path = "../ox-rpc" }
ox-text = { path = "../ox-text" }
ox-types = { path = "../ox-types" }
thiserror.workspace = true
unicode-width = "0.2.2"

[lints]
workspace = true
