//! The `api-metadata` dictionary returned by `nvim_get_api_info`, plus the
//! response tuple `[channel_id, metadata]`.
//!
//! # Upstream mapping
//!
//! The schema is generated by `src/gen/gen_api_metadata.lua`. Top-level keys
//! and orders there: `version` (with `major`/`minor`/`patch`/`prerelease`/
//! `api_level`/`api_compatible`/`api_prerelease` + `build`), `functions`,
//! `ui_events`, `ui_options`, `error_types`, `types`. We append `custom_events`
//! (a newer metadata key) after `types`.
//!
//!   - `error_types` is `{ Exception: { id: 0 }, Validation: { id: 1 } }`.
//!   - `types` is the "Ext" handle map, one entry per handle kind:
//!     `{ id, prefix }` with `Buffer`→0/`nvim_buf_`, `Window`→1/`nvim_win_`,
//!     `Tabpage`→2/`nvim_tabpage_`.
//!   - `version.api_level` is `15` for the API this crate targets;
//!     `api_compatible` is `0`.
//!
//! The `channel_id` of the `[channel_id, metadata]` response is filled in by
//! the server per incoming request, so it is set through [`Self::set_channel_id`]
//! rather than baked into the dictionary.

use ox_types::{Dict, Object, OxStr};

/// Decode the canonical Neovim 0.13 API-level-15 metadata table.
///
/// The checked-in value is generated from the reference binary's `--api-info`
/// output so function inventory, optional parameters, flags, UI events, and
/// top-level key presence remain one indivisible protocol contract.
pub fn canonical_metadata() -> Result<Object, crate::DecodeError> {
    crate::decode(include_bytes!("api_metadata.msgpack"))
}

/// The API level the metadata advertises (`NVIM_API_LEVEL` for 0.13).
pub const API_LEVEL: i64 = 15;
/// The lowest API level this build is backward-compatible with.
pub const API_COMPATIBLE: i64 = 0;

/// Builder for the api-metadata dictionary.
#[derive(Debug, Clone)]
pub struct ApiMetadata {
    major: i64,
    minor: i64,
    patch: i64,
    prerelease: bool,
    api_prerelease: bool,
    build: OxStr,
    functions: Vec<Object>,
    ui_events: Vec<Object>,
    ui_options: Vec<OxStr>,
    custom_events: Vec<Object>,
    channel_id: u64,
}

impl Default for ApiMetadata {
    fn default() -> Self {
        Self::new()
    }
}

impl ApiMetadata {
    /// Fresh metadata for a 0.1.0-style build with `api_level = 15`
    /// and the `rgb` UI option (upstream seeds `ui_options` with `"rgb"`).
    #[must_use]
    pub fn new() -> Self {
        Self {
            major: 0,
            minor: 1,
            patch: 0,
            prerelease: false,
            api_prerelease: false,
            build: OxStr::from(""),
            functions: Vec::new(),
            ui_events: Vec::new(),
            ui_options: vec![OxStr::from("rgb")],
            custom_events: Vec::new(),
            channel_id: 0,
        }
    }

    /// Set the Nvim-style version tuple.
    pub fn set_version(&mut self, major: i64, minor: i64, patch: i64, prerelease: bool) {
        self.major = major;
        self.minor = minor;
        self.patch = patch;
        self.prerelease = prerelease;
    }

    /// Set the build string (`version.build`).
    pub fn set_build(&mut self, build: impl Into<OxStr>) {
        self.build = build.into();
    }

    /// Mark the API as unreleased (`version.api_prerelease`).
    pub fn set_api_prerelease(&mut self, prerelease: bool) {
        self.api_prerelease = prerelease;
    }

    /// The channel id used to fill the `[channel_id, metadata]` response pair.
    pub fn set_channel_id(&mut self, id: u64) {
        self.channel_id = id;
    }

    /// Register a function signature (populated by the `#[api]` macro later).
    pub fn add_function(&mut self, function: Object) {
        self.functions.push(function);
    }

    /// Register a UI event signature.
    pub fn add_ui_event(&mut self, event: Object) {
        self.ui_events.push(event);
    }

    /// Register an additional supported UI option (beyond the default `"rgb"`).
    pub fn add_ui_option(&mut self, option: impl Into<OxStr>) {
        self.ui_options.push(option.into());
    }

    /// Register a custom (non-`nvim_*`) event name.
    pub fn add_custom_event(&mut self, name: impl Into<OxStr>) {
        self.custom_events.push(Object::String(name.into()));
    }

    /// Build the metadata dictionary.
    #[must_use]
    pub fn metadata_object(&self) -> Object {
        let mut metadata = Dict(vec![]);
        metadata.insert(OxStr::from("version"), self.version_object());
        metadata.insert(
            OxStr::from("functions"),
            Object::Array(self.functions.clone()),
        );
        metadata.insert(OxStr::from("ui_events"), Object::Array(self.ui_events.clone()));
        metadata.insert(
            OxStr::from("ui_options"),
            Object::Array(
                self.ui_options
                    .iter()
                    .map(|o| Object::String(o.clone()))
                    .collect(),
            ),
        );
        metadata.insert(OxStr::from("error_types"), error_types_object());
        metadata.insert(OxStr::from("types"), handle_types_object());
        metadata.insert(
            OxStr::from("custom_events"),
            Object::Array(self.custom_events.clone()),
        );
        Object::Dict(metadata)
    }

    /// Build the full `nvim_get_api_info` response `[channel_id, metadata]`.
    #[must_use]
    pub fn api_info_object(&self) -> Object {
        Object::Array(vec![Object::Integer(self.channel_id as i64), self.metadata_object()])
    }

    fn version_object(&self) -> Object {
        let mut v = Dict(vec![]);
        v.insert(OxStr::from("major"), Object::Integer(self.major));
        v.insert(OxStr::from("minor"), Object::Integer(self.minor));
        v.insert(OxStr::from("patch"), Object::Integer(self.patch));
        v.insert(OxStr::from("prerelease"), Object::Boolean(self.prerelease));
        v.insert(OxStr::from("api_level"), Object::Integer(API_LEVEL));
        v.insert(OxStr::from("api_compatible"), Object::Integer(API_COMPATIBLE));
        v.insert(OxStr::from("api_prerelease"), Object::Boolean(self.api_prerelease));
        v.insert(OxStr::from("build"), Object::String(self.build.clone()));
        Object::Dict(v)
    }
}

/// `error_types` — `{ Exception: { id: 0 }, Validation: { id: 1 } }`.
fn error_types_object() -> Object {
    let mut error_types = Dict(vec![]);
    error_types.insert(
        OxStr::from("Exception"),
        Object::Dict(Dict(vec![(OxStr::from("id"), Object::Integer(0))])),
    );
    error_types.insert(
        OxStr::from("Validation"),
        Object::Dict(Dict(vec![(OxStr::from("id"), Object::Integer(1))])),
    );
    Object::Dict(error_types)
}

/// `types` — the handle kind map with `{ id, prefix }` per entry.
fn handle_types_object() -> Object {
    let mut types = Dict(vec![]);
    for (name, id, prefix) in [
        ("Buffer", 0, "nvim_buf_"),
        ("Window", 1, "nvim_win_"),
        ("Tabpage", 2, "nvim_tabpage_"),
    ] {
        types.insert(
            OxStr::from(name),
            Object::Dict(Dict(vec![
                (OxStr::from("id"), Object::Integer(id)),
                (OxStr::from("prefix"), Object::String(OxStr::from(prefix))),
            ])),
        );
    }
    Object::Dict(types)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]
    use super::*;

    fn get<'a>(obj: &'a Object, key: &str) -> &'a Object {
        match obj {
            Object::Dict(d) => d.get(&OxStr::from(key)).expect("key present"),
            _ => panic!("not a dict"),
        }
    }

    fn int(obj: &Object) -> i64 {
        match obj {
            Object::Integer(n) => *n,
            _ => panic!("not an integer"),
        }
    }

    #[test]
    fn metadata_has_all_schema_keys() {
        let meta = ApiMetadata::new().metadata_object();
        for key in [
            "version",
            "functions",
            "ui_events",
            "ui_options",
            "error_types",
            "types",
            "custom_events",
        ] {
            assert!(get(&meta, key) != &Object::Nil, "missing key {key}");
        }
    }

    #[test]
    fn api_level_is_15() {
        let meta = ApiMetadata::new().metadata_object();
        let version = get(&meta, "version");
        assert_eq!(int(get(version, "api_level")), 15);
        assert_eq!(int(get(version, "api_compatible")), 0);
        assert_eq!(int(get(version, "major")), 0);
        // build defaults to the empty string.
        assert_eq!(get(version, "build"), &Object::String(OxStr::from("")));
    }

    #[test]
    fn error_types_match_schema() {
        let meta = ApiMetadata::new().metadata_object();
        let err = get(&meta, "error_types");
        assert_eq!(int(get(get(err, "Exception"), "id")), 0);
        assert_eq!(int(get(get(err, "Validation"), "id")), 1);
    }

    #[test]
    fn handle_types_match_schema() {
        let meta = ApiMetadata::new().metadata_object();
        let types = get(&meta, "types");
        assert_eq!(int(get(get(types, "Buffer"), "id")), 0);
        assert_eq!(get(get(types, "Buffer"), "prefix"), &Object::String(OxStr::from("nvim_buf_")));
        assert_eq!(int(get(get(types, "Window"), "id")), 1);
        assert_eq!(get(get(types, "Window"), "prefix"), &Object::String(OxStr::from("nvim_win_")));
        assert_eq!(int(get(get(types, "Tabpage"), "id")), 2);
        assert_eq!(
            get(get(types, "Tabpage"), "prefix"),
            &Object::String(OxStr::from("nvim_tabpage_"))
        );
    }

    #[test]
    fn registrable_surfaces() {
        let mut m = ApiMetadata::new();
        m.add_function(Object::Dict(Dict(vec![(OxStr::from("name"), Object::String(OxStr::from("nvim_x")))])));
        m.add_ui_event(Object::Nil);
        m.add_ui_option("ext_linegrid");
        m.add_custom_event("Bla");
        m.set_channel_id(3);
        assert_eq!(
            get(&m.metadata_object(), "custom_events"),
            &Object::Array(vec![Object::String(OxStr::from("Bla"))])
        );
        let info = m.api_info_object();
        match &info {
            Object::Array(parts) => {
                assert_eq!(parts.len(), 2);
                assert_eq!(parts[0], Object::Integer(3));
            }
            _ => panic!("api info must be a 2-tuple"),
        }
    }

    #[test]
    fn canonical_metadata_preserves_oracle_shape() {
        let metadata = canonical_metadata().unwrap();
        let Object::Dict(root) = &metadata else { panic!("metadata must be a dictionary") };
        let keys: Vec<_> = root.0.iter().map(|(key, _)| key.to_string_lossy()).collect();
        assert_eq!(keys, ["version", "functions", "ui_events", "ui_options", "error_types", "types"]);
        let Object::Array(functions) = get(&metadata, "functions") else { panic!("functions must be an array") };
        assert_eq!(functions.len(), 262);
        let Object::Array(parameters) = get(&functions[0], "parameters") else { panic!("parameters must be an array") };
        assert!(matches!(parameters[0], Object::Array(ref fields) if fields.len() == 3));
    }
}