[package]
name = "ox-eval"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Vimscript expression lexer, parser, evaluator, and scopes"

[lints]
workspace = true

[dependencies]
ox-sys = { path = "../ox-sys" }
ox-types = { path = "../ox-types" }
serde_json.workspace = true
thiserror.workspace = true
