//! Generates byte-embedded Neovim Lua builtin modules.

use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::io::{self, ErrorKind};
use std::path::{Path, PathBuf};

// Neovim's src/nvim/CMakeLists.txt:647-673 defines the inputs and requires
// vim._init_packages and vim.inspect to be first and second. The generated
// builtin_modules table gives the authoritative complete order; see
// build/src/nvim/auto/lua/vim_module.generated.h:16744-16810.
const BUILTIN_MODULES: &[(&str, &str)] = &[
    ("vim._init_packages", "vim/_init_packages.lua"),
    ("vim.inspect", "vim/inspect.lua"),
    ("vim.filetype", "vim/filetype.lua"),
    ("vim.fs", "vim/fs.lua"),
    ("vim.F", "vim/F.lua"),
    ("vim.keymap", "vim/keymap.lua"),
    ("vim.loader", "vim/loader.lua"),
    ("vim.text", "vim/text.lua"),
    ("vim.tty", "vim/tty.lua"),
    ("vim._core.cmdwin", "vim/_core/cmdwin.lua"),
    ("vim._core.defaults", "vim/_core/defaults.lua"),
    ("vim._core.editor", "vim/_core/editor.lua"),
    ("vim._core.ex_cmd", "vim/_core/ex_cmd.lua"),
    ("vim._core.exmode", "vim/_core/exmode.lua"),
    ("vim._core.exrc", "vim/_core/exrc.lua"),
    ("vim._core.help", "vim/_core/help.lua"),
    ("vim._core.log", "vim/_core/log.lua"),
    ("vim._core.marks", "vim/_core/marks.lua"),
    ("vim._core.options", "vim/_core/options.lua"),
    ("vim._core.proc", "vim/_core/proc.lua"),
    ("vim._core.server", "vim/_core/server.lua"),
    ("vim._core.shared", "vim/_core/shared.lua"),
    ("vim._core.spell", "vim/_core/spell.lua"),
    ("vim._core.stringbuffer", "vim/_core/stringbuffer.lua"),
    ("vim._core.swapfile", "vim/_core/swapfile.lua"),
    ("vim._core.system", "vim/_core/system.lua"),
    ("vim._core.table", "vim/_core/table.lua"),
    ("vim._core.tag", "vim/_core/tag.lua"),
    ("vim._core.time", "vim/_core/time.lua"),
    ("vim._core.ui", "vim/_core/ui.lua"),
    ("vim._core.ui2", "vim/_core/ui2.lua"),
    ("vim._core.util", "vim/_core/util.lua"),
    ("vim._core.vimfn", "vim/_core/vimfn.lua"),
];

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-env-changed=OXVIM_REF_ROOT");

    let runtime_root = match env::var_os("OXVIM_REF_ROOT") {
        Some(reference_root) => {
            let reference_root = PathBuf::from(reference_root);
            if !reference_root.is_dir() {
                return Err(io::Error::new(
                    ErrorKind::NotFound,
                    format!(
                        "OXVIM_REF_ROOT does not name a directory: {}",
                        reference_root.display()
                    ),
                )
                .into());
            }
            reference_root.join("runtime")
        }
        None => {
            let manifest_dir = env::var_os("CARGO_MANIFEST_DIR").ok_or_else(|| {
                io::Error::new(
                    ErrorKind::NotFound,
                    "OXVIM_REF_ROOT is unset and Cargo did not provide CARGO_MANIFEST_DIR",
                )
            })?;
            let fallback = PathBuf::from(manifest_dir).join("../../runtime");
            if !fallback.is_dir() {
                return Err(io::Error::new(
                    ErrorKind::NotFound,
                    format!(
                        "OXVIM_REF_ROOT is unset and the checked-out runtime is missing: {}",
                        fallback.display()
                    ),
                )
                .into());
            }
            fallback
        }
    };
    if !runtime_root.is_dir() {
        return Err(io::Error::new(
            ErrorKind::NotFound,
            format!(
                "Neovim runtime root is missing: {}",
                runtime_root.display()
            ),
        )
        .into());
    }

    let source_root = runtime_root.join("lua");
    let out_dir = env::var_os("OUT_DIR")
        .ok_or_else(|| io::Error::new(ErrorKind::NotFound, "Cargo did not provide OUT_DIR"))?;
    let out_dir = Path::new(&out_dir);
    let mut generated = String::from(
        "// @generated by crates/ox-lua/build.rs; do not edit.\n\
         pub(crate) struct EmbeddedModule {\n\
             pub(crate) name: &'static str,\n\
             pub(crate) source_name: &'static str,\n\
             pub(crate) bytes: &'static [u8],\n\
         }\n\n\
         pub(crate) static EMBEDDED_MODULES: &[EmbeddedModule] = &[\n",
    );

    for (index, (name, relative_source)) in BUILTIN_MODULES.iter().enumerate() {
        let source = source_root.join(relative_source);
        println!("cargo:rerun-if-changed={}", source.display());
        let bytes = fs::read(&source).map_err(|error| {
            io::Error::new(
                error.kind(),
                format!(
                    "missing Neovim builtin source {} for module {name}: {error}",
                    source.display()
                ),
            )
        })?;
        let embedded_filename = format!("ox_lua_builtin_{index:02}.lua");
        write_if_changed(&out_dir.join(&embedded_filename), &bytes)?;
        writeln!(
            generated,
            "    EmbeddedModule {{ name: {name:?}, source_name: {source_name:?}, bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{embedded_filename}\")) }},",
            source_name = format!("@{relative_source}"),
        )?;
    }
    generated.push_str("];\n");
    write_if_changed(&out_dir.join("ox_lua_embedded.rs"), generated.as_bytes())?;
    Ok(())
}

fn write_if_changed(path: &Path, bytes: &[u8]) -> io::Result<()> {
    match fs::read(path) {
        Ok(existing) if existing == bytes => Ok(()),
        Ok(_) | Err(_) => fs::write(path, bytes),
    }
}
