// Generated from Neovim 0.13 API level 15 metadata.
use crate::{FunctionMetadata, TypeRef};

pub(crate) const API_FUNCTIONS: &[FunctionMetadata] = &[
    FunctionMetadata {
        name: "nvim_get_autocmds",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Dict),
        params: &[
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_create_autocmd",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("event", TypeRef::Object, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_del_autocmd",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("id", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_clear_autocmds",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_create_augroup",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("name", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_del_augroup_by_id",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("id", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_del_augroup_by_name",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_exec_autocmds",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("event", TypeRef::Object, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_line_count",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_attach",
        since: 4,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("send_buffer", TypeRef::Boolean, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_detach",
        since: 4,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_lines",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::String),
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("start", TypeRef::Integer, false),
            ("end", TypeRef::Integer, false),
            ("strict_indexing", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_lines",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("start", TypeRef::Integer, false),
            ("end", TypeRef::Integer, false),
            ("strict_indexing", TypeRef::Boolean, false),
            ("replacement", TypeRef::ArrayOf(&TypeRef::String), false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_text",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("start_row", TypeRef::Integer, false),
            ("start_col", TypeRef::Integer, false),
            ("end_row", TypeRef::Integer, false),
            ("end_col", TypeRef::Integer, false),
            ("replacement", TypeRef::ArrayOf(&TypeRef::String), false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_text",
        since: 9,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::String),
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("start_row", TypeRef::Integer, false),
            ("start_col", TypeRef::Integer, false),
            ("end_row", TypeRef::Integer, false),
            ("end_col", TypeRef::Integer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_offset",
        since: 5,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("index", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_changedtick",
        since: 2,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_keymap",
        since: 3,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Dict),
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("mode", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_keymap",
        since: 6,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("mode", TypeRef::String, false),
            ("lhs", TypeRef::String, false),
            ("rhs", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_del_keymap",
        since: 6,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("mode", TypeRef::String, false),
            ("lhs", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_del_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_name",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_name",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_is_loaded",
        since: 5,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_delete",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_is_valid",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_del_mark",
        since: 8,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_mark",
        since: 8,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
            ("line", TypeRef::Integer, false),
            ("col", TypeRef::Integer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_mark",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Named("ArrayOf(Integer, 2)"),
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_call",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("fn", TypeRef::LuaRef, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_parse_cmd",
        since: 10,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("str", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_cmd",
        since: 10,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("cmd", TypeRef::Dict, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_create_user_command",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
            ("cmd", TypeRef::Object, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_del_user_command",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_create_user_command",
        since: 9,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
            ("cmd", TypeRef::Object, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_del_user_command",
        since: 9,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_commands",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_commands",
        since: 4,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_exec",
        since: 7,
        deprecated_since: Some(11),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("src", TypeRef::String, false),
            ("output", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_command_output",
        since: 1,
        deprecated_since: Some(7),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("command", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_execute_lua",
        since: 3,
        deprecated_since: Some(7),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("code", TypeRef::String, false),
            ("args", TypeRef::Array, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_number",
        since: 1,
        deprecated_since: Some(2),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buffer", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_clear_highlight",
        since: 1,
        deprecated_since: Some(7),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("line_start", TypeRef::Integer, false),
            ("line_end", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_add_highlight",
        since: 1,
        deprecated_since: Some(13),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("hl_group", TypeRef::String, false),
            ("line", TypeRef::Integer, false),
            ("col_start", TypeRef::Integer, false),
            ("col_end", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_virtual_text",
        since: 5,
        deprecated_since: Some(8),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("src_id", TypeRef::Integer, false),
            ("line", TypeRef::Integer, false),
            ("chunks", TypeRef::Array, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_hl_by_id",
        since: 3,
        deprecated_since: Some(9),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("hl_id", TypeRef::Integer, false),
            ("rgb", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_hl_by_name",
        since: 3,
        deprecated_since: Some(9),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("name", TypeRef::String, false),
            ("rgb", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_insert",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("lnum", TypeRef::Integer, false),
            ("lines", TypeRef::ArrayOf(&TypeRef::String), false),
        ],
    },
    FunctionMetadata {
        name: "buffer_get_line",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("index", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_set_line",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("index", TypeRef::Integer, false),
            ("line", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_del_line",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("index", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_get_line_slice",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::String),
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("start", TypeRef::Integer, false),
            ("end", TypeRef::Integer, false),
            ("include_start", TypeRef::Boolean, false),
            ("include_end", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_set_line_slice",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("start", TypeRef::Integer, false),
            ("end", TypeRef::Integer, false),
            ("include_start", TypeRef::Boolean, false),
            ("include_end", TypeRef::Boolean, false),
            ("replacement", TypeRef::ArrayOf(&TypeRef::String), false),
        ],
    },
    FunctionMetadata {
        name: "buffer_set_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_del_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "window_set_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("window", TypeRef::Window, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "window_del_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("window", TypeRef::Window, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "tabpage_set_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "tabpage_del_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_set_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "vim_del_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_option_info",
        since: 7,
        deprecated_since: Some(11),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_option",
        since: 1,
        deprecated_since: Some(11),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_option",
        since: 1,
        deprecated_since: Some(11),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_option",
        since: 1,
        deprecated_since: Some(11),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_option",
        since: 1,
        deprecated_since: Some(11),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_option",
        since: 1,
        deprecated_since: Some(11),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("window", TypeRef::Window, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_set_option",
        since: 1,
        deprecated_since: Some(11),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("window", TypeRef::Window, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_call_atomic",
        since: 1,
        deprecated_since: Some(12),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Array,
        params: &[
            ("calls", TypeRef::Array, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_subscribe",
        since: 1,
        deprecated_since: Some(13),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("event", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_unsubscribe",
        since: 1,
        deprecated_since: Some(13),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("event", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_out_write",
        since: 1,
        deprecated_since: Some(13),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("str", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_err_write",
        since: 1,
        deprecated_since: Some(13),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("str", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_err_writeln",
        since: 1,
        deprecated_since: Some(13),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("str", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_notify",
        since: 7,
        deprecated_since: Some(13),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("msg", TypeRef::String, false),
            ("log_level", TypeRef::Integer, false),
            ("opts", TypeRef::Dict, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_set_height",
        since: 1,
        deprecated_since: Some(15),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("height", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_set_width",
        since: 1,
        deprecated_since: Some(15),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("width", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_term_event",
        since: 12,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("event", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_create_namespace",
        since: 5,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_namespaces",
        since: 5,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_extmark_by_id",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Array,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("id", TypeRef::Integer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_get_extmarks",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Dict),
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("start", TypeRef::Object, false),
            ("end", TypeRef::Object, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_set_extmark",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("line", TypeRef::Integer, false),
            ("col", TypeRef::Integer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_del_extmark",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("id", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_buf_clear_namespace",
        since: 5,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("line_start", TypeRef::Integer, false),
            ("line_end", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_decoration_provider",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("ns_id", TypeRef::Integer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_option_value",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_option_value",
        since: 9,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_all_options_info",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_option_info2",
        since: 11,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("name", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_tabpage_list_wins",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Window),
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_tabpage_get_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_tabpage_set_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_tabpage_del_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_tabpage_get_win",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Window,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_tabpage_set_win",
        since: 12,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_tabpage_get_number",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_tabpage_is_valid",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_open_tabpage",
        since: 14,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Tabpage,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("enter", TypeRef::Boolean, false),
            ("config", TypeRef::Dict, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_attach",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("width", TypeRef::Integer, false),
            ("height", TypeRef::Integer, false),
            ("options", TypeRef::Dict, false),
        ],
    },
    FunctionMetadata {
        name: "ui_attach",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("width", TypeRef::Integer, false),
            ("height", TypeRef::Integer, false),
            ("enable_rgb", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_set_focus",
        since: 11,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("gained", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_detach",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_try_resize",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("width", TypeRef::Integer, false),
            ("height", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_set_option",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_try_resize_grid",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("grid", TypeRef::Integer, false),
            ("width", TypeRef::Integer, false),
            ("height", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_pum_set_height",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("height", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_pum_set_bounds",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("width", TypeRef::Float, false),
            ("height", TypeRef::Float, false),
            ("row", TypeRef::Float, false),
            ("col", TypeRef::Float, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_ui_send",
        since: 14,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("content", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_hl_id_by_name",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_hl",
        since: 11,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("ns_id", TypeRef::Integer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_hl",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("ns_id", TypeRef::Integer, false),
            ("name", TypeRef::String, false),
            ("val", TypeRef::Dict, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_hl_ns",
        since: 12,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_hl_ns",
        since: 10,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("ns_id", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_hl_ns_fast",
        since: 10,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("ns_id", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_feedkeys",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("keys", TypeRef::String, false),
            ("mode", TypeRef::String, false),
            ("escape_ks", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_input",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("keys", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_input_mouse",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("button", TypeRef::String, false),
            ("action", TypeRef::String, false),
            ("modifier", TypeRef::String, false),
            ("grid", TypeRef::Integer, false),
            ("row", TypeRef::Integer, false),
            ("col", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_replace_termcodes",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("str", TypeRef::String, false),
            ("from_part", TypeRef::Boolean, false),
            ("do_lt", TypeRef::Boolean, false),
            ("special", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_exec_lua",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("code", TypeRef::String, false),
            ("args", TypeRef::Array, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_strwidth",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("text", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_list_runtime_paths",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::String),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_runtime_file",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::String),
        params: &[
            ("name", TypeRef::String, false),
            ("all", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_current_dir",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("dir", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_current_line",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_set_current_line",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("line", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_del_current_line",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_var",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_var",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_del_var",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_vvar",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_vvar",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_echo",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("chunks", TypeRef::ArrayOf(&TypeRef::Array), false),
            ("history", TypeRef::Boolean, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_list_bufs",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Buffer),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_current_buf",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Buffer,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_set_current_buf",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_list_wins",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Window),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_current_win",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Window,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_set_current_win",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_create_buf",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Buffer,
        params: &[
            ("listed", TypeRef::Boolean, false),
            ("scratch", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_open_term",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_chan_send",
        since: 7,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("chan", TypeRef::Integer, false),
            ("data", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_list_tabpages",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Tabpage),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_current_tabpage",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Tabpage,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_set_current_tabpage",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_paste",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("data", TypeRef::String, false),
            ("crlf", TypeRef::Boolean, false),
            ("phase", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_put",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("lines", TypeRef::ArrayOf(&TypeRef::String), false),
            ("type", TypeRef::String, false),
            ("after", TypeRef::Boolean, false),
            ("follow", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_color_by_name",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_color_map",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_context",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_load_context",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("dict", TypeRef::Dict, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_mode",
        since: 2,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_keymap",
        since: 3,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Dict),
        params: &[
            ("mode", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_set_keymap",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("mode", TypeRef::String, false),
            ("lhs", TypeRef::String, false),
            ("rhs", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_del_keymap",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("mode", TypeRef::String, false),
            ("lhs", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_api_info",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Named("ArrayOf(Object, 2)"),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_set_client_info",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
            ("version", TypeRef::Dict, false),
            ("type", TypeRef::String, false),
            ("methods", TypeRef::Dict, false),
            ("attributes", TypeRef::Dict, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_chan_info",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("chan", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_list_chans",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Dict),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_list_uis",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Dict),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "nvim_get_proc_children",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Array,
        params: &[
            ("pid", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_proc",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("pid", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_select_popupmenu_item",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("item", TypeRef::Integer, false),
            ("insert", TypeRef::Boolean, false),
            ("finish", TypeRef::Boolean, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_del_mark",
        since: 8,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_get_mark",
        since: 8,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Array,
        params: &[
            ("name", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_eval_statusline",
        since: 8,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("str", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_exec2",
        since: 11,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("src", TypeRef::String, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_command",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("cmd", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_eval",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("expr", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_call_function",
        since: 1,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("fn", TypeRef::String, false),
            ("args", TypeRef::Array, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_call_dict_function",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("dict", TypeRef::Object, false),
            ("fn", TypeRef::String, false),
            ("args", TypeRef::Array, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_parse_expression",
        since: 4,
        deprecated_since: None,
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("expr", TypeRef::String, false),
            ("flags", TypeRef::String, false),
            ("hl", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_open_win",
        since: 6,
        deprecated_since: None,
        method: false,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Window,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("enter", TypeRef::Boolean, false),
            ("config", TypeRef::Dict, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_set_config",
        since: 6,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("config", TypeRef::Dict, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_config",
        since: 6,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_buf",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Buffer,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_set_buf",
        since: 5,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_cursor",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Named("ArrayOf(Integer, 2)"),
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_set_cursor",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("pos", TypeRef::Named("ArrayOf(Integer, 2)"), false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_height",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_width",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("win", TypeRef::Window, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_set_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_del_var",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_position",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Named("ArrayOf(Integer, 2)"),
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_tabpage",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Tabpage,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_get_number",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_is_valid",
        since: 1,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_hide",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_close",
        since: 6,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: true,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("force", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_call",
        since: 7,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("win", TypeRef::Window, false),
            ("fn", TypeRef::LuaRef, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_set_hl_ns",
        since: 10,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("ns_id", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_text_height",
        since: 12,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
            ("win", TypeRef::Window, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "nvim_win_resize",
        since: 15,
        deprecated_since: None,
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("width", TypeRef::Integer, false),
            ("height", TypeRef::Integer, false),
            ("opts", TypeRef::Dict, true),
        ],
    },
    FunctionMetadata {
        name: "buffer_line_count",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_get_lines",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::String),
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("start", TypeRef::Integer, false),
            ("end", TypeRef::Integer, false),
            ("strict_indexing", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_set_lines",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("start", TypeRef::Integer, false),
            ("end", TypeRef::Integer, false),
            ("strict_indexing", TypeRef::Boolean, false),
            ("replacement", TypeRef::ArrayOf(&TypeRef::String), false),
        ],
    },
    FunctionMetadata {
        name: "buffer_get_var",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_get_name",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_set_name",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_is_valid",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_get_mark",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Named("ArrayOf(Integer, 2)"),
        params: &[
            ("buf", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_command_output",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("command", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_get_number",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buffer", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_clear_highlight",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("line_start", TypeRef::Integer, false),
            ("line_end", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_add_highlight",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("ns_id", TypeRef::Integer, false),
            ("hl_group", TypeRef::String, false),
            ("line", TypeRef::Integer, false),
            ("col_start", TypeRef::Integer, false),
            ("col_end", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "vim_set_option",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "vim_get_option",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_get_option",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "buffer_set_option",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buffer", TypeRef::Buffer, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "window_get_option",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("window", TypeRef::Window, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "window_set_option",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("window", TypeRef::Window, false),
            ("name", TypeRef::String, false),
            ("value", TypeRef::Object, false),
        ],
    },
    FunctionMetadata {
        name: "vim_subscribe",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("event", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_unsubscribe",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("event", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_out_write",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("str", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_err_write",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("str", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_report_error",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("str", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "window_set_height",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("height", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "window_set_width",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("width", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "tabpage_get_windows",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Window),
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "tabpage_get_var",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "tabpage_get_window",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Window,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "tabpage_is_valid",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "ui_detach",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "ui_try_resize",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("width", TypeRef::Integer, false),
            ("height", TypeRef::Integer, false),
        ],
    },
    FunctionMetadata {
        name: "vim_feedkeys",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("keys", TypeRef::String, false),
            ("mode", TypeRef::String, false),
            ("escape_ks", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "vim_input",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("keys", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_replace_termcodes",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
            ("str", TypeRef::String, false),
            ("from_part", TypeRef::Boolean, false),
            ("do_lt", TypeRef::Boolean, false),
            ("special", TypeRef::Boolean, false),
        ],
    },
    FunctionMetadata {
        name: "vim_strwidth",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("text", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_list_runtime_paths",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::String),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_change_directory",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("dir", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_get_current_line",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::String,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_set_current_line",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("line", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_del_current_line",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_get_var",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_get_vvar",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_get_buffers",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Buffer),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_get_current_buffer",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Buffer,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_set_current_buffer",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("buf", TypeRef::Buffer, false),
        ],
    },
    FunctionMetadata {
        name: "vim_get_windows",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Window),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_get_current_window",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Window,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_set_current_window",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "vim_get_tabpages",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::ArrayOf(&TypeRef::Tabpage),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_get_current_tabpage",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Tabpage,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_set_current_tabpage",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("tabpage", TypeRef::Tabpage, false),
        ],
    },
    FunctionMetadata {
        name: "vim_name_to_color",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_get_color_map",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Dict,
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_get_api_info",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: true,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Named("ArrayOf(Object, 2)"),
        params: &[
        ],
    },
    FunctionMetadata {
        name: "vim_command",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("cmd", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_eval",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("expr", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "vim_call_function",
        since: 0,
        deprecated_since: Some(1),
        method: false,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("fn", TypeRef::String, false),
            ("args", TypeRef::Array, false),
        ],
    },
    FunctionMetadata {
        name: "window_get_buffer",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Buffer,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "window_get_cursor",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Named("ArrayOf(Integer, 2)"),
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "window_set_cursor",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Void,
        params: &[
            ("win", TypeRef::Window, false),
            ("pos", TypeRef::Named("ArrayOf(Integer, 2)"), false),
        ],
    },
    FunctionMetadata {
        name: "window_get_height",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "window_get_width",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Integer,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "window_get_var",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Object,
        params: &[
            ("win", TypeRef::Window, false),
            ("name", TypeRef::String, false),
        ],
    },
    FunctionMetadata {
        name: "window_get_position",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Named("ArrayOf(Integer, 2)"),
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "window_get_tabpage",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Tabpage,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
    FunctionMetadata {
        name: "window_is_valid",
        since: 0,
        deprecated_since: Some(1),
        method: true,
        fast: false,
        textlock: false,
        textlock_allow: false,
        returns: TypeRef::Boolean,
        params: &[
            ("win", TypeRef::Window, false),
        ],
    },
];
